### ISSUE TITLE
vs. rabbitmq/ra

### ISSUE THREAD

**Issue by sashaafm** [toniqsystems/raft#13]
Hello, I'd like to know what are the differences and benefits/disadvantages between this project and `rabbitmq/ra`?

Thanks!

**Comment by NeilMenne** [comment]
Hi, @sashaafm. Chris addressed a similar question in the elixir forums [here](https://elixirforum.com/t/6-lonestar-elixirconf-2018-consistent-distributed-elixir-chris-keathley/13246/6).

The important part in my words:
Ra has intentionally/explicitly deviated from the raft specification with respect to failure detection. Also, it handles the complexities of the log directly with files where we've chosen to use rocksdb (though it is pluggable). There are several cases around the log that are extremely important to get right (especially during leadership changes), so we chose to use something that made those cases easier to reason about.
