### ISSUE TITLE
Question: Is raft a good fit for just managing leadership?

### ISSUE THREAD

**Issue by brainlid** [toniqsystems/raft#15]
I realize the primary purpose of Raft is around managing a replicated log.

I'm trying to determine if this project is an appropriate fit for just helping to manage service leadership in a cluster? My feeling is "no".

**Comment by keathley** [comment]
Hey @brainlid! This is actually a question that comes up a lot. The TL;DR is No. You can't just take raft's leader election and use it to determine a leader in a cluster. Here's an example:

Imagine that you have a cluster of 3 nodes. A leader has been elected. The leader maintains a view of the world and accepts all reads and writes. It is partitioned away from a majority of nodes. The other nodes elect a new leader. Once the partition heals how do you determine which of those leaders is correct? Typically you would use the log to do that. If you don't have a log then you have to invent some other way to choose the correct leader which may or may not actually work for your use case.

The important thing to remember is that Raft uses leader election as a means of reaching *consensus* for a value. In all reality, consensus is the only reason to use a leader election mechanism in the first place. So disregarding the fundamental data structure (the log) is really just asking for trouble.

Now, if you need to provide leader election for an external service (similar to how people use zookeeper) then what you can do is build a state machine on top of Raft that can do a compare and swap operation. A super naive way in code would look something like this:

```elixir
defmodule Leader do
  use Raft.StateMachine

  def handle_read(:current_leader, leader) do
    {leader, leader}
  end

  def handle_write({:set, new_leader, current_leader}, current_leader) do
    {{:ok, new_leader}, new_leader}
  end
  def handle_write({:set, _, _}, current_leader) do
    {{:error, current_leader}, current_leader}
  end
end
```

In reality you would need to add a TTL and have nodes continue to elect themselves.
